### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by guy120494** [Enigmatis/graphql-java-annotations#101]
Is this library still under maintenance? If not, can I become a maintainer? I need this library for my work so it is important to me

**Comment by yrashk** [comment]
Hi Guy, 

Original author here. The GraphQL project has suspended my maintainer privileges for the time being as I wasn't active maintaining it. You can ask to become a maintainer on GraphQL's Gitter channel: https://gitter.im/graphql-java/graphql-java

Alternatively, I can pick up project maintenance and, time-permitting, further project evolution. However, since I don't have immediate use for this project, I have to prioritize how I spend my time. If you're interested in having me resume work and maintenance on this library, please consider becoming my patron on Patreon: https://www.patreon.com/yrashk. I have created a special reward called "Project boost: GraphQL Java Annotations + Servlet". The more funding I can raise the more time I'll be able to dedicate to this project.

**Comment by guy120494** [comment]
I became a maintainer. Thanks a lot
