### ISSUE TITLE
When a field value is null (is nullable) returns No GraphQL field Found

### ISSUE THREAD

**Issue by noamski** [Enigmatis/graphql-java-annotations#218]
When I'm trying to fetch a field using inheritanced interfaces and the value of the field is null,
even if it is nullable it throws a noSuchFieldExceptionError at MethodDataFetcher.java in the method getGraphQLFieldValue.

**Comment by Fgerthoffert** [comment]
Hi @noamski,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,
