### ISSUE TITLE
Allow interface to extend another interface

### ISSUE THREAD

**Issue by OfirCohen28101999** [Enigmatis/graphql-java-annotations#219]
For example:
Class A implements interface B
interface B extends interface C

But it does not recognize interface B as children of C

**Comment by yarinvak** [comment]
Unfortunately the graphql spec does not support an interface that extends another interface.
You can view discussion here https://github.com/graphql/graphql-spec/pull/373
It seems that it intends to support it soon, but we will have to wait for graphql-java to support it too.

**Comment by Fgerthoffert** [comment]
Hi @OfirCohen28101999,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,
