### ISSUE TITLE
extending type doesn't support interface

### ISSUE THREAD

**Issue by BleicherMagic** [Enigmatis/graphql-java-annotations#265]
Hi, I created an a extended class with GraphQLTypeExtension annotaion and added interface to it and when i checked the generated schema i didn't see that my type extended this interface
example:
`@GraphQLName("IcdAsset")
public class IcdAsset extends IcdEntity {}

@GraphQLTypeExtension(IcdAsset.class)
public class IcdAssetExtended implements EntityCommonInterfaceType {
}
@GraphQLTypeResolver(MockResolver.class)
public interface EntityCommonInterfaceType {}

Generated schema:
type IcdAsset {
}(should be type IcdAsset extends EntityCommonInterfaceType)
`

**Comment by Fgerthoffert** [comment]
Hi @BleicherMagic  ,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,
