### ISSUE TITLE
Support spring-graphql

### ISSUE THREAD

**Issue by cn-src** [Enigmatis/graphql-java-annotations#275]
spring-graphql annotations `@GraphQlController`, `@QueryMapping`, `@SubscriptionMapping`, `@MutationMapping`.

**Comment by yarinvak** [comment]
Please elaborate.
`graphql-java-annotations` can be integrated with spring, but it's not spring specific, therefore we will not add spring as a dependency here.

**Comment by StringKe** [comment]
> Please elaborate. `graphql-java-annotations` can be integrated with spring, but it's not spring specific, therefore we will not add spring as a dependency here.

How to generate schema for these annotations via graphql-java-annotations ?

**Comment by Fgerthoffert** [comment]
Hi @cn-src  ,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,

**Comment by Fgerthoffert** [comment]
Hi,

We are not going to introduce a dependency to spring, this is a different framework.

We're closing this issue as not relevant for this project.

Thanks
