### ISSUE TITLE
Should allow for specialized constructor @GraphQLDataFetcher

### ISSUE THREAD

**Issue by crazyfrozenpenguin** [Enigmatis/graphql-java-annotations#39]
I've noticed that GraphQL will, for fields starting with "is" (e.g. isAvailable), set the DataFetcher to FieldDataFetcher as opposed to PropertyDataFetcher.

Native boolean fields starting by "isXxxx" are allowed to have a getter method of the same name as defined in the [Java Beans spec](http://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf?AuthParam=1481464050_3f25905d9013aa13d325e7f69c044b62) section 8.3.2:

```java
   public boolean is<PropertyName>();
```

The same is not necessarily true for Boolean object types.

Although it is discussible if such fields should be using FieldDataFetcher by default, the graphql-java-annotations should allow graphql fields to be easily overwritten by another DataFetcher basic type.

The current case generates a FieldDataFetcher by default:

```kotlin
  @ApiModelProperty(value = "")
  @GraphQLField
  var isAvailable: Boolean? = null
```

But instead I would like it to use the PropertyDataFetcher:

```kotlin
  @ApiModelProperty(value = "")
  @GraphQLField
  @GraphQLDataFetcher(PropertyDataFetcher::class)
  var isAvailable: Boolean? = null
```

And this code fails to compile because PropertyDataFetcher annotation does not have a public default constructor. To get around it I had to specialize the PropertyDataFetcher for that specific field and it can become quite repetitive having to do the same for other similar fields.

Instead, it would be nice to allow to pass argument for a given specialized constructor as in:

```java
  @GraphQLDataFetcher(value=PropertyDataFetcher::class, args="isAvailable")
  public Boolean isAvailable = null
```

**Comment by yrashk** [comment]
It's an interesting idea. Mind sending a PR?

**Comment by bmsantos** [comment]
GraphQL is Object Type Agnostic. Because of it there's no guarantee that the data object composition used to build the graph will be of the exact same type as the one returned from the DataFetcher.

PR #44 introduces a test that verifies such case. The TestGraphQLQuery uses the SampleDataFetcher to provide a TestSample instance. Because GraphQL does not care about class types (it cares only that the passed instance has the expected fields), the SampleDataFetcher ends-up returning a Sample instance instead of the TestSample used to create the graph. 

The TestSample instance exposes a private field that by default, GrapQL, will set to use the FieldDataFetcher. The problem with this is that this data fetcher will not work when a Sample instance is returned because the field is private. In such case, a specialized PropertyDataFetcher must be set. Allowing the @GraphQLDataFetcher to pass arguments to a constructor will minimize the number of specialized instances to be created for each-and-every single field.

For example, a class with two fields:
```java
class Is {
  @GraphQLField @GraphQLDataFetcher(IsGreatDataFetcher.class)
  private Boolean isGreat;
  @GraphQLField @GraphQLDataFetcher(IsAmazingDataFetcher.class)
  private Boolean isAmazing;
}
```

Would require the following DataFetchers:

```java
public class IsGreatDataFetcher extends PropertyDataFetcher {
  IsGreatDataFetcher() {
    super("isGreat");
  }
}

public class IsAmazingDataFetcher extends PropertyDataFetcher {
  IsAmazingDataFetcher() {
    super("isAmazing");
  }
}
```

By allowing constructor arguments, we can simplify it to just:

```java
class Is {
  @GraphQLField @GraphQLDataFetcher(value = PropertyDataFetcher.class, args = "isGreat")
  private Boolean isGreat;
  @GraphQLField @GraphQLDataFetcher(value = PropertyDataFetcher.class, args = "isAmazing")
  private Boolean isAmazing;
}
```

**Comment by crazyfrozenpenguin** [comment]
This works just fine. Thanks. Closing issue.
