### ISSUE TITLE
Support of inherited interfaces

### ISSUE THREAD

**Issue by mattesja** [Enigmatis/graphql-java-annotations#65]
Only direct implemented interfaces are supported when building a GraphQLObjectType.

class MyObject implements MyInterface {} => OK

class MyObject2 extends MyObject {} => No interface in ObjectType

ClassUtils.getAllInterfaces(object) should be used instead of object.getInterfaces()

Would you accept such a pull request adding such a dependency on apache-commons-lang?

**Comment by guy120494** [comment]
Please make a PR

**Comment by Fgerthoffert** [comment]
Hi @mattesja,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed). 

Thanks,

**Comment by richharms** [comment]
While not the original reporter, I am still interested in this and will try to put together a PR for it.

**Comment by sergehuber** [comment]
Any update on the PR ? Otherwise we can close this issue ?

**Comment by richharms** [comment]
My apologizes for not getting to this sooner, let me see if I can put something together in the next week. Congrats on a great release, BTW! Easiest one I believe I've ever had for a complex project that integrates this library.

**Comment by Fgerthoffert** [comment]
Thanks for the PR @richharms , we will be reviewing it soon.

**Comment by Fgerthoffert** [comment]
The PR was merged, we are closing the ticket.
