### ISSUE TITLE
Updating graphql-java

### ISSUE THREAD

**Issue by athlordJojo** [Enigmatis/graphql-java-annotations#73]
Is there a reason why graphql-java is still using version 2.2.0 ?
Why not using 2.3.0 ?

**Comment by bbakerman** [comment]
if GraphQLInvokeDetached is on a method then a new instance of that class will be instatiated and then the method will be invoked on it

this covers the (some what rare imho) case when you want a new instance of an object rather than a singleton from the context.

in general the "object" upon which to invoke the method upon comes from the "graphql" execution environment

    @Override
    public Object get(DataFetchingEnvironment environment) {
        try {
            Object obj;

            if (Modifier.isStatic(method.getModifiers())) {
                obj = null;
            } else if (method.getAnnotation(GraphQLInvokeDetached.class) == null) {
                obj = environment.getSource();
                if (obj == null) {
                    return null;
                }
            } else {
                obj = newInstance(method.getDeclaringClass());
            }
            return method.invoke(obj, invocationArgs(environment));
        } catch (IllegalAccessException | InvocationTargetException e) {
            throw new RuntimeException(e);
        }
    }
