### ISSUE TITLE
What does  @GraphQLInvokeDetached do?

### ISSUE THREAD

**Issue by JakMa123** [Enigmatis/graphql-java-annotations#74]
Inside the sourcecode i stumbled upon the `@GraphQLInvokeDetached` annotation. Could you explain what it is used for?

**Comment by athlordJojo** [comment]
me too, please explain

**Comment by bbakerman** [comment]
GraphQLInvokeDetached will instantiate a new object and then invoked the annotated method to get its values

By default the MethodDataFetcher will use the context object to invoke the method on.  This allows you to "new" up a new instance of an object

    @Override
    public Object get(DataFetchingEnvironment environment) {
        try {
            Object obj;

            if (Modifier.isStatic(method.getModifiers())) {
                obj = null;
            } else if (method.getAnnotation(GraphQLInvokeDetached.class) == null) {
                obj = environment.getSource();
                if (obj == null) {
                    return null;
                }
            } else {
                obj = newInstance(method.getDeclaringClass());
            }
            return method.invoke(obj, invocationArgs(environment));
        } catch (IllegalAccessException | InvocationTargetException e) {
            throw new RuntimeException(e);
        }
    }

In general I think using the context is more sensible because graphql decends down a tree of objects, using ones previously resolved as the context for the next one and so on.

But this allows you to break out of this behaviour if you like
