### ISSUE TITLE
Extract EnhancedExecutionStrategy into separate module (or project)

### ISSUE THREAD

**Issue by apottere** [Enigmatis/graphql-java-annotations#75]
EnhancedExecutionStrategy (really Relay.js execution strategy) doesn't really seem to belong in the same module as the rest of the annotation processing, since it can be used separately.

I'd like to include it as a dependency in `graphql-java-servlet` without requiring the use of annotations - would it be possible to create a new module or project (graphql-java-executioncontexts? :P ) for it that deploys a separate jarfile?

**Comment by apottere** [comment]
I feel like having a project full of different execution contexts could be very useful.

**Comment by apottere** [comment]
I'd be happy to start the other project, as well.

**Comment by Fgerthoffert** [comment]
Hi @apottere,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,

**Comment by apottere** [comment]
Thanks for checking in, I'm no longer interested in this.
