### ISSUE TITLE
Publish package to maven central

### ISSUE THREAD

**Issue by sunilnirmal** [Enigmatis/graphql-java-annotations#89]
Kindly publish the version having support for graphql-java-3.0.0 to maven central

**Comment by istvan-fodor** [comment]
I second that. I have a project that uses graphql-java-annotations and this would be very helpful.

**Comment by danielocampo2** [comment]
An alternative to this is to use jitpack. In this case, you can use: https://jitpack.io/#graphql-java/graphql-java-annotations
Follow instructions to add jitpack repo based on the build system you are using and you'll be able to get any branch / commit you want.

**Comment by bbakerman** [comment]
OK so I had a lot of trouble getting BinTray to work and then JCenter publishing so then it can go to Maven Central

Fingers cross its there.


On JCenter it seems to be there

https://bintray.com/graphql-java/graphql-java-annotations/graphql-java-annotations/3.0.2

And it says it has synced to Maven Central

     Last Synced: Mon Jun 26 08:53:11 GMT 2017
     Last Sync Status: Successfully synced and closed repo.
     Last Sync Errors: N/A

but I cant see it in maven.org yet.  Some one says this can take a while.   So fingers crossed

Its 3.0.2 because I burnt a few numbers on the way trying to get Bintray to work

**Comment by danielocampo2** [comment]
It is published already: https://mvnrepository.com/artifact/com.graphql-java/graphql-java-annotations
Thanks!

**Comment by lsiu** [comment]
@sunilnirmal close the issue since it is publish to maven central?

**Comment by sunilnirmal** [comment]
Thanks!
