### ISSUE TITLE
new release date to support graphql-java 4.x

### ISSUE THREAD

**Issue by imrikoch** [Enigmatis/graphql-java-annotations#97]
I would like to know when a new version is expected to be released .
i know that a new version of graphql-java is expected to be released at end of August.

**Comment by guy120494** [comment]
I would also like to know when (and if) this library is going to be built on graphql 4.1.0.
I no one intends to do so, I would be happy to make the PR, but I want to know that it is going to be merged (if it passed the code review)

**Comment by yrashk** [comment]
Hi @imrikoch, 

Original author here. The GraphQL project has suspended my maintainer privileges for the time being as I wasn't active maintaining it. You can ask to become a maintainer on GraphQL's Gitter channel: https://gitter.im/graphql-java/graphql-java

Alternatively, I can pick up project maintenance and, time-permitting, further project evolution. However, since I don't have immediate use for this project, I have to prioritize how I spend my time. If you're interested in having me resume work and maintenance on this library, please consider becoming my patron on Patreon: https://www.patreon.com/yrashk. I have created a special reward called "Project boost: GraphQL Java Annotations + Servlet". The more funding I can raise the more time I'll be able to dedicate to this project.

**Comment by assafey** [comment]
+1

**Comment by guy120494** [comment]
Hi @imrikoch.
I have just been added as a maintainer, So I will start working on that when I have the time (hopefully soon).
You are welcome to help me and @yarinvak

**Comment by guy120494** [comment]
Upgraded to 4.2

**Comment by assafey** [comment]
@guy120494 when will it be published to maven repo?

**Comment by guy120494** [comment]
We need to do a few fixes (like fix the connection) and then we will publish it
